let tab = [
    {name:"Ania",chances:6,rarity:"common",photo:"./img/testowe/1.png"},
    {name:"Ania",chances:7,rarity:"common",photo:"./img/testowe/2.png"},
    {name:"Ania",chances:1,rarity:"common",photo:"./img/testowe/3.png"},
    {name:"Ania",chances:7,rarity:"common",photo:"./img/testowe/4.png"},
    {name:"Ania",chances:6,rarity:"common",photo:"./img/testowe/5.png"},
    {name:"Ania",chances:7,rarity:"common",photo:"./img/testowe/6.png"},
    {name:"Ania",chances:6,rarity:"common",photo:"./img/testowe/7.png"},
    {name:"Ania",chances:7,rarity:"common",photo:"./img/testowe/8.png"},
    {name:"Ania",chances:6,rarity:"common",photo:"./img/testowe/9.png"},
    {name:"Ania",chances:7,rarity:"common",photo:"./img/testowe/10.png"},
    {name:"Ania",chances:6,rarity:"common",photo:"./img/testowe/11.png"},
    {name:"Ania",chances:7,rarity:"common",photo:"./img/testowe/12.png"},
    {name:"Ania",chances:6,rarity:"common",photo:"./img/testowe/13.png"},
    {name:"Ania",chances:7,rarity:"common",photo:"./img/testowe/14.png"},
    {name:"Ania",chances:6,rarity:"common",photo:"./img/testowe/15.png"},
    {name:"Ania",chances:7,rarity:"common",photo:"./img/testowe/16.png"},
    {name:"Ania",chances:5,rarity:"common",photo:"./img/testowe/17.png"}
]
